### ISSUE TITLE
Linux ? 

### ISSUE THREAD

**Issue by FULCOS** [yasserjanah/FacebookChecker#1]
Comment peut on l'utiliser avec Linux ?

**Comment by yasserjanah** [comment]
Tu as deux choix, tu peux installer la version executable [click here](https://github.com/yasserjanah/FacebookChecker/releases/download/v1.0/FacebookChecker_linux_amd64.tar.xz) et tu peux l'éxecuter depuis le terminal.
ou tu peux installer language go sur ton machine et tu peux facilement utiliser la commande **go install github.com/yasserjanah/FacebookChecker@latest** pour l'installer.
