### ISSUE TITLE
can import goland working?

### ISSUE THREAD

**Issue by ifour2022** [yasserjanah/FacebookChecker#3]
hi 
can import goland working?

**Comment by yasserjanah** [comment]
Hi, what do you mean?
if you facing any issue, kindly describe your problem.

**Comment by ifour2022** [comment]
I want to integrate your program into my system, it's a web application, it doesn't use the command line, it's like an api for checking, but I'm a novice, just learning go language, so I want to ask you

Sent with a Spark
2022年3月13日 +0800 17:12 Yasser Janah ***@***.***>，写道：

**Comment by yasserjanah** [comment]
It's Okay, you can modify the code, it's totally free, if it is an interesting project, contact me if you need help.
