### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by michaell10** [yasserjanah/FacebookChecker#7]
it tells me after the installation that the command FacebookChecker isn't found, I think i messed it up with the installation.
Can you give me an in depth step by step commands for the installation and setup?

**Comment by d4r14h** [comment]
You probably have to add Go to PATH

**Comment by RiteshSec** [comment]
@d4r14h I am facing the same issue here. I have cross checked if Go is Added to path and it is. 

However I have also tried running the main.go manually and am getting like this 
<img width="609" alt="image" src="https://github.com/yasserjanah/FacebookChecker/assets/110530131/478ea12b-7991-425a-9607-00fc560c690c">

Can you help me how to resolve the above error. 

@yasserjanah

**Comment by yasserjanah** [comment]
@RiteshSec You can execute the program using the command `go run main.go requester.go`. Alternatively, you can download the executable version directly from [https://github.com/yasserjanah/FacebookChecker/releases/tag/v1.0](https://github.com/yasserjanah/FacebookChecker/releases/tag/v1.0)

**Comment by RiteshSec** [comment]
Thank You @yasserjanah got it working

**Comment by hassaan211** [comment]
The executable version exe file is not opening on windows @yasserjanah help!

**Comment by yasserjanah** [comment]
@hassaan211 Could you share additional details about this problem, along with a screenshot?

**Comment by hassaan211** [comment]
in video u can see the exe file is not opening and keeps crashing.
@yasserjanah 
https://github.com/yasserjanah/FacebookChecker/assets/143750805/8d9c639f-8864-49e5-a5b0-89429d4361b7

**Comment by yasserjanah** [comment]
@hassaan211 you should execute it from the command line.

<img src="https://raw.githubusercontent.com/yasserjanah/FacebookChecker/main/screenshots/windows_example.png" />

**Comment by hassaan211** [comment]
I also entered another account but it is not giving information :(
@yasserjanah
![image](https://github.com/yasserjanah/FacebookChecker/assets/143750805/c7fd4521-c8ad-4e99-9f62-82226e3e3c65)
